title: "mily's website"
email: me@mily.ovh
description: My awesome webpage!
baseurl: ""
url: "https://mily.ovh" 
github_username:  milyd
telegram_username: "milusii"

plugins:
  - jekyll-feed
  - jekyll-sitemap