title: "mily's website"
email: me@mily.ovh
description: My awesome website!
baseurl: ""
url: "https://mily.ovh" 
github_username:  milyd
telegram_username: "milusii"
matrix_username: "@mily:matrix.mily.ovh"
plugins:
  - jekyll-feed
  - jekyll-sitemap